server:
  port: 8089

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    content-type: text/html
    enabled: true
    encoding: UTF-8
    mode: HTML5

  resources:
    add-mappings: true
    chain:
      cache: true
      enabled: true
      html-application-cache: true
    static-locations: classpath:/static/

  security:
    user:
      name: test
      password: 123456
      roles: admin
mybatis-plus:
  mapper-locations: classpath:com/eale/auth/mapper/*.xml
  type-aliases-package: com.eale.auth.entity
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      #逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: mysql
    refresh: false
